defaultNamespace: default
helm:
  chart: https://github.com/rancherfederal/rancher-cluster-templates/releases/download/rancher-cluster-templates-0.4.3/rancher-cluster-templates-0.4.3.tgz
  releaseName: aws-rke2-prod-cluster
  valuesFiles:
    - ../values.yaml
    - ./prod-values.yaml
diff:
   comparePatches:
   - apiVersion: provisioning.cattle.io/v1
     kind: Cluster
     namespace: fleet-default
     name: aws-rke2-prod-cluster
     operations:
     - {"op": "remove", "path": "/spec/localClusterAuthEndpoint"}
     - {"op": "remove", "path": "/spec/rkeConfig/machinePools"}
     - {"op": "remove", "path": "/spec/rkeConfig/registries/configs/rgcrprod.azurecr.us"}
     - {"op": "remove", "path": "/spec/rkeConfig/machineSelectorConfig"}
