apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: {{ .Values.application.project }}
  source:
    repoURL: {{ .Values.application.source.repoURL }}
    targetRevision: {{ .Values.application.source.targetRevision }}
    path: {{ .Values.application.source.path }}
    helm:
      values: |
{{ .Values.application.source.helm.values | indent 8 }}
  destination:
    server: {{ .Values.application.destination.server }}
    namespace: {{ .Values.application.destination.namespace }}