defaultNamespace: argocd

labels:
  app: argocd

helm:
  repo: oci://harbor.atoy.dev/public/argo-cd
  version: 7.4.6
  releaseName: argocd
  valuesFiles:
  - values.yaml

targetCustomizations:
- name: prod
  helm:
    valuesFiles:
    - prod-values.yaml
  clusterSelector:
    matchLabels:
      env: prod
- name: staging
  helm:
    valuesFiles:
    - staging-values.yaml
  clusterSelector:
    matchLabels:
      env: staging