apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: harvester-rke2-staging-cluster
  namespace: fleet-local
spec:
  repo: git@github.com:atoy3731/fleet-argo-bootstrap.git
  branch: staging
  clientSecretName: fleet-argo-bootstrap-key
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
  paths:
  - ./infrastructure/harvester/staging