defaultNamespace: demo-app

helm:
  chart: ./chart
  releaseName: demo-app

labels:
  app: demo-app

dependsOn:
  - selector:
      matchLabels:
        app: argocd

targetCustomizations:
- name: prod
  helm:
    valuesFiles:
    - prod-values.yaml
  clusterSelector:
    matchLabels:
      env: prod
- name: staging
  helm:
    valuesFiles:
    - staging-values.yaml
  clusterSelector:
    matchLabels:
      env: staging