application:
  project: default
  source:
    repoURL: https://github.com/atoy3731/rancher-app.git
    targetRevision: helm
    path: "./helm/chart"
    helm:
      values: |+
        foo: bar
  destination:
    server: https://kubernetes.default.svc
    namespace: demo